const path = require('path');

const projectRoot = path.resolve(__dirname, '..', '..');
const documentRoot = path.join(
  projectRoot,
  'docs/codex/2026-07-27-perfect-orbit-day-private-planner-rebuild',
);
const designRoot = path.join(documentRoot, 'design');
const outputRoot = path.join(designRoot, '01-foundations/stage10-theme');
const manifestRoot = path.join(designRoot, '04-copy-manifests');

const catalogVersion = 'ps01-theme-2.0.0';
const direction = 'Graphite Bloom / Perfect Day Instrument';

const themes = Object.freeze({
  light: Object.freeze({
    id: 'theme-light-daylight',
    label: 'Daylight',
    brightness: 'light',
    contrast: 'standard',
    canvas: '#FFFCF7',
    canvasAccent: '#FFF4E8',
    surfaceLowest: '#FFFFFF',
    surfaceLow: '#FFFAF4',
    surface: '#FBF6EF',
    surfaceHigh: '#F4EEE7',
    surfaceHighest: '#EEE7DF',
    glass: '#F7FFFFFF',
    glassStrong: '#FCFFFFFF',
    ink: '#1D2030',
    muted: '#605D70',
    primary: '#9D4C0B',
    onPrimary: '#FFFFFF',
    primaryVivid: '#FFA34D',
    primaryContainer: '#FFE6CF',
    onPrimaryContainer: '#462000',
    secondary: '#2F7650',
    onSecondary: '#FFFFFF',
    secondaryVivid: '#7EC99B',
    secondaryContainer: '#DDF3E5',
    onSecondaryContainer: '#123622',
    tertiary: '#6652AD',
    onTertiary: '#FFFFFF',
    tertiaryVivid: '#A79ADD',
    tertiaryContainer: '#EEEAFD',
    onTertiaryContainer: '#2E245F',
    sync: '#16796F',
    syncContainer: '#D8F3EF',
    onSyncContainer: '#073B37',
    warning: '#855300',
    warningContainer: '#FFF0C2',
    onWarningContainer: '#3E2600',
    danger: '#B53145',
    dangerContainer: '#FFE1E5',
    onDangerContainer: '#650E20',
    outline: '#777280',
    outlineVariant: '#DDD4CB',
    focus: '#8E4208',
    shadow: '#244B3D32',
    blur: 18,
    blurStrong: 26,
  }),
  dark: Object.freeze({
    id: 'theme-dark-graphite-bloom',
    label: 'Graphite Bloom',
    brightness: 'dark',
    contrast: 'standard',
    canvas: '#141620',
    canvasAccent: '#201E2B',
    surfaceLowest: '#11131B',
    surfaceLow: '#1A1D28',
    surface: '#202331',
    surfaceHigh: '#292D3D',
    surfaceHighest: '#323648',
    glass: '#E81E2230',
    glassStrong: '#F5282C3C',
    ink: '#F9F7FF',
    muted: '#C9C5D4',
    primary: '#FFC184',
    onPrimary: '#2A1200',
    primaryVivid: '#FFB66C',
    primaryContainer: '#4C3322',
    onPrimaryContainer: '#FFE3C4',
    secondary: '#A8DFB9',
    onSecondary: '#092115',
    secondaryVivid: '#8FD8A8',
    secondaryContainer: '#233B2D',
    onSecondaryContainer: '#D8F5E1',
    tertiary: '#D1C6FF',
    onTertiary: '#1C143B',
    tertiaryVivid: '#BCADF4',
    tertiaryContainer: '#36314E',
    onTertiaryContainer: '#ECE7FF',
    sync: '#74D8CD',
    syncContainer: '#173D3A',
    onSyncContainer: '#CBFFF8',
    warning: '#FFD17A',
    warningContainer: '#4B360D',
    onWarningContainer: '#FFF0C7',
    danger: '#FFB2BB',
    dangerContainer: '#512832',
    onDangerContainer: '#FFE0E4',
    outline: '#9B97AA',
    outlineVariant: '#5A5F72',
    focus: '#FFD0A2',
    shadow: '#7A080910',
    blur: 18,
    blurStrong: 26,
  }),
  highContrastLight: Object.freeze({
    id: 'theme-hc-light-clarity',
    label: 'Clarity Light',
    brightness: 'light',
    contrast: 'high',
    canvas: '#FFFFFF',
    canvasAccent: '#FFFFFF',
    surfaceLowest: '#FFFFFF',
    surfaceLow: '#F7F7F9',
    surface: '#FFFFFF',
    surfaceHigh: '#E8E8EC',
    surfaceHighest: '#D9D9DF',
    glass: '#FFFFFFFF',
    glassStrong: '#FFFFFFFF',
    ink: '#090A0F',
    muted: '#292B35',
    primary: '#6D2E00',
    onPrimary: '#FFFFFF',
    primaryVivid: '#9B4300',
    primaryContainer: '#FFF0E1',
    onPrimaryContainer: '#160900',
    secondary: '#145D34',
    onSecondary: '#FFFFFF',
    secondaryVivid: '#207A47',
    secondaryContainer: '#E8F8EE',
    onSecondaryContainer: '#062012',
    tertiary: '#3E2A82',
    onTertiary: '#FFFFFF',
    tertiaryVivid: '#5740A5',
    tertiaryContainer: '#F0ECFF',
    onTertiaryContainer: '#10072E',
    sync: '#00564F',
    syncContainer: '#E1FFFB',
    onSyncContainer: '#001F1C',
    warning: '#633D00',
    warningContainer: '#FFF4CC',
    onWarningContainer: '#211300',
    danger: '#8C1025',
    dangerContainer: '#FFE8EB',
    onDangerContainer: '#2F000A',
    outline: '#4A4B55',
    outlineVariant: '#70717D',
    focus: '#6D2E00',
    shadow: '#00000000',
    blur: 0,
    blurStrong: 0,
  }),
  highContrastDark: Object.freeze({
    id: 'theme-hc-dark-clarity',
    label: 'Clarity Dark',
    brightness: 'dark',
    contrast: 'high',
    canvas: '#000000',
    canvasAccent: '#000000',
    surfaceLowest: '#000000',
    surfaceLow: '#050609',
    surface: '#08090D',
    surfaceHigh: '#171922',
    surfaceHighest: '#242630',
    glass: '#FF08090D',
    glassStrong: '#FF08090D',
    ink: '#FFFFFF',
    muted: '#F0EDF7',
    primary: '#FFD1A3',
    onPrimary: '#100700',
    primaryVivid: '#FFBD7C',
    primaryContainer: '#3B1D00',
    onPrimaryContainer: '#FFF0DF',
    secondary: '#AEF2C4',
    onSecondary: '#001308',
    secondaryVivid: '#89E4A7',
    secondaryContainer: '#092B19',
    onSecondaryContainer: '#E2FFEA',
    tertiary: '#DED4FF',
    onTertiary: '#11092F',
    tertiaryVivid: '#C5B7FF',
    tertiaryContainer: '#21174F',
    onTertiaryContainer: '#F4F0FF',
    sync: '#99FFF3',
    syncContainer: '#003D38',
    onSyncContainer: '#E0FFFB',
    warning: '#FFE59A',
    warningContainer: '#422C00',
    onWarningContainer: '#FFF5D8',
    danger: '#FFC2C8',
    dangerContainer: '#490716',
    onDangerContainer: '#FFECEF',
    outline: '#FFFFFF',
    outlineVariant: '#A6A6B0',
    focus: '#FFD1A3',
    shadow: '#00000000',
    blur: 0,
    blurStrong: 0,
  }),
});

const candidates = Object.freeze([
  Object.freeze({
    id: 'candidate-graphite-bloom',
    title: 'Graphite Bloom',
    subtitle: 'Neutral graphite depth with pastel light, quiet glass and explicit boundaries.',
    palette: themes.dark,
    score: 96,
    verdict: 'SELECTED — strongest Perfect identity, calm long-session use and clean Windows hierarchy.',
  }),
  Object.freeze({
    id: 'candidate-midnight-vellum',
    title: 'Midnight Vellum',
    subtitle: 'Warmer plum-charcoal paper with softer apricot light and low-gloss material.',
    palette: Object.freeze({
      ...themes.dark,
      canvas: '#19151C',
      canvasAccent: '#281F29',
      surfaceLow: '#211C25',
      surface: '#28212C',
      surfaceHigh: '#342B38',
      outlineVariant: '#615464',
      primary: '#FFD0A0',
      secondary: '#B4E4BE',
      tertiary: '#DCC8FF',
    }),
    score: 84,
    verdict: 'REJECTED — warm and attractive, but dense planning surfaces become too cocoa/muddy.',
  }),
  Object.freeze({
    id: 'candidate-ink-prism',
    title: 'Ink Prism',
    subtitle: 'Near-black technical canvas with brighter spectral accents and sharper separators.',
    palette: Object.freeze({
      ...themes.dark,
      canvas: '#0C0E15',
      canvasAccent: '#131827',
      surfaceLow: '#141823',
      surface: '#191E2B',
      surfaceHigh: '#232A3B',
      outlineVariant: '#59627A',
      primary: '#FFC17B',
      secondary: '#8BE5B0',
      tertiary: '#C7BBFF',
      sync: '#7DEBE0',
    }),
    score: 89,
    verdict: 'REJECTED — excellent focus, but too cyber/technical for a humane private day planner.',
  }),
]);

const contrastPairs = Object.freeze([
  ['ink', 'canvas', 4.5, 'primary text'],
  ['muted', 'surface', 4.5, 'secondary text'],
  ['primary', 'surface', 4.5, 'primary action on surface'],
  ['onPrimary', 'primary', 4.5, 'filled primary action'],
  ['onPrimaryContainer', 'primaryContainer', 4.5, 'primary container copy'],
  ['secondary', 'surface', 4.5, 'habit/rhythm foreground'],
  ['onSecondary', 'secondary', 4.5, 'filled rhythm action'],
  ['onSecondaryContainer', 'secondaryContainer', 4.5, 'rhythm container copy'],
  ['tertiary', 'surface', 4.5, 'focus/reflection foreground'],
  ['onTertiary', 'tertiary', 4.5, 'filled focus action'],
  ['onTertiaryContainer', 'tertiaryContainer', 4.5, 'focus container copy'],
  ['sync', 'surface', 4.5, 'synced status label'],
  ['onSyncContainer', 'syncContainer', 4.5, 'sync container copy'],
  ['warning', 'surface', 4.5, 'syncing/retrying label'],
  ['onWarningContainer', 'warningContainer', 4.5, 'warning container copy'],
  ['danger', 'surface', 4.5, 'error label'],
  ['onDangerContainer', 'dangerContainer', 4.5, 'error container copy'],
  ['outline', 'surface', 3, 'interactive boundary'],
  ['focus', 'surface', 3, 'focus perimeter'],
]);

module.exports = {
  projectRoot,
  documentRoot,
  designRoot,
  outputRoot,
  manifestRoot,
  catalogVersion,
  direction,
  themes,
  candidates,
  contrastPairs,
};
